@startuml

package "这三个结构被分配在连续的内存空间" <<Rectangle>> {
    class "struct mmc_host" as mmc {
        struct device		*parent;
        struct device		class_dev;
        int			index;
        const struct mmc_host_ops *ops;
        const struct mmc_cmdq_host_ops *cmdq_ops;
        ...
        unsigned long private[0] ____cacheline_aligned;
    }

    class "struct sdhci_host" as host {
        ...
        const struct sdhci_ops *ops;
        ..Internal data..
        struct mmc_host *mmc;
        ...
        unsigned long private[0] ____cacheline_aligned;
    }

    class "struct sdhci_pltfm_host" as pltfm_host {
        struct clk *clk;
        void *priv;
        unsigned int clock;
        u16 xfer_mode_shadow;
    }
}

class "struct sdhci_msm_host" as msm_host {
    ...
    struct sdhci_msm_pltfm_data *pdata;
    struct mmc_host  *mmc;
    ==struct sdhci_pltfm_data==
    const struct sdhci_ops *ops;
    unsigned int quirks;
    ==
    ...
}

class "struct sdhci_msm_pltfm_data" as pdata {
    u32 caps;
    u32 caps2;
    unsigned long mmc_bus_width;
    struct sdhci_msm_slot_reg_data *vreg_data;
    bool nonremovable;
    bool use_mod_dynamic_qos;
    bool nonhotplug;
    bool broken_pwr_cycle_host;
    bool no_1p8v;
    bool largeaddressbus;
    bool pin_cfg_sts;
    struct sdhci_msm_pin_data *pin_data;
    struct sdhci_pinctrl_data *pctrl_data;
    u32 *cpu_dma_latency_us;
    unsigned int cpu_dma_latency_tbl_sz;
    int status_gpio;
    struct sdhci_msm_bus_voting_data *voting_data;
    u32 *sup_clk_table;
    unsigned char sup_clk_cnt;
    int mpm_sdiowakeup_int;
    int sdiowakeup_irq;
    enum pm_qos_req_type cpu_affinity_type;
    cpumask_t cpu_affinity_mask;
    u32 *sup_ice_clk_table;
    unsigned char sup_ice_clk_cnt;
    u32 ice_clk_max;
    u32 ice_clk_min;
    bool core_3_0v_support;
}

interface "static const struct mmc_host_ops sdhci_ops" as sdhci_ops {
    .pre_req	= sdhci_pre_req,
    .post_req	= sdhci_post_req,
    .request	= sdhci_request,
    .set_ios	= sdhci_set_ios,
    .get_cd		= sdhci_get_cd,
    .get_ro		= sdhci_get_ro,
    .hw_reset	= sdhci_hw_reset,
    .enable_sdio_irq = sdhci_enable_sdio_irq,
    .start_signal_voltage_switch	= sdhci_start_signal_voltage_switch,
    .execute_tuning			= sdhci_execute_tuning,
    .enhanced_strobe		= sdhci_enhanced_strobe,
    .card_event			= sdhci_card_event,
    .card_busy	= sdhci_card_busy,
    .enable		= sdhci_enable,
    .disable	= sdhci_disable,
    .stop_request = sdhci_stop_request,
    .get_xfer_remain = sdhci_get_xfer_remain,
    .notify_load	= sdhci_notify_load,
    .notify_halt	= sdhci_notify_halt,
    .notify_pm_status	= sdhci_notify_pm_status,
}

interface "static struct sdhci_ops sdhci_msm_ops" as sdhci_msm_ops {
    .crypto_engine_cfg = sdhci_msm_ice_cfg,
    .crypto_cfg_reset = sdhci_msm_ice_cfg_reset,
    .crypto_engine_reset = sdhci_msm_ice_reset,
    .platform_reset_enter = sdhci_msm_reset_enter,
    .set_uhs_signaling = sdhci_msm_set_uhs_signaling,
    .check_power_status = sdhci_msm_check_power_status,
    .execute_tuning = sdhci_msm_execute_tuning,
    .enhanced_strobe = sdhci_msm_enhanced_strobe,
    .toggle_cdr = sdhci_msm_toggle_cdr,
    .get_max_segments = sdhci_msm_max_segs,
    .set_clock = sdhci_msm_set_clock,
    .get_min_clock = sdhci_msm_get_min_clock,
    .get_max_clock = sdhci_msm_get_max_clock,
    .disable_data_xfer = sdhci_msm_disable_data_xfer,
    .dump_vendor_regs = sdhci_msm_dump_vendor_regs,
    .config_auto_tuning_cmd = sdhci_msm_config_auto_tuning_cmd,
    .enable_controller_clock = sdhci_msm_enable_controller_clock,
    .reset_workaround = sdhci_msm_reset_workaround,
    .clear_set_dumpregs = sdhci_msm_clear_set_dumpregs,
    .notify_load = sdhci_msm_notify_load,
    .notify_pm_status = sdhci_msm_notify_pm_status,
    .enhanced_strobe_mask = sdhci_msm_enhanced_strobe_mask,
}

mmc "ops" -right-> sdhci_ops
mmc "private" -down-> host
host "private" -down-> pltfm_host
host "ops" --> sdhci_msm_ops
host "mmc" -up-> mmc
pltfm_host "priv" -right-> msm_host
msm_host "pdata" -right-> pdata
msm_host "mmc" --> mmc
msm_host "sdhci_pltfm_data.ops" --> sdhci_msm_ops


@enduml
