@startuml

!include ../../include/sequence.iuml

title ufs_qcom_probe

box "ufs"
participant "ufs-qcom.c" as ufs_qcom order 1
participant "ufshcd-pltfrm.c" as ufshcd_pltfrm order 2
participant "ufshcd.c" as ufshcd order 3
end box

box "scsi"
participant "scsi_scan.c" as scsi_scan order 4
end box

[->ufs_qcom : ufs_qcom_probe

call(ufs_qcom, ufshcd_pltfrm, ufshcd_pltfrm_init)
call(ufshcd_pltfrm, ufshcd, ufshcd_alloc_host)
return(ufshcd_pltfrm, ufshcd, ufshcd_alloc_host)
call(ufshcd_pltfrm, ufshcd, ufshcd_init)
call_self_async(ufshcd, ufshcd_async_scan)
call_self(ufshcd, ufshcd_probe_hba)
call_self(ufshcd, ufshcd_link_startup)
return_self(ufshcd, ufshcd_link_startup)
call_self(ufshcd, ufshcd_scsi_add_wlus)
call(ufshcd, scsi_scan, __scsi_add_device)
call_self(scsi_scan, scsi_probe_and_add_lun)
return_self(scsi_scan, scsi_probe_and_add_lun)
return(ufshcd, scsi_scan, __scsi_add_device)
return_self(ufshcd, ufshcd_scsi_add_wlus)
return_self(ufshcd, ufshcd_probe_hba)
return_self_async(ufshcd, ufshcd_async_scan)
return(ufshcd_pltfrm, ufshcd, ufshcd_init)
return(ufs_qcom, ufshcd_pltfrm, ufshcd_pltfrm_init)

[<--ufs_qcom : //--ufs_qcom_probe--//

@enduml
